// Generated by CoffeeScript 1.12.2

/**
 * @function hello
 * Create a welcoming message which includes a name
 * @param {name} String name
 * @return {string} Personalized welcome message
 */

(function() {
  var Animal, dog, goodbye, hello;

  hello = function(name) {
    return console.log('Hello ', name);
  };


  /**
   * @function goodbye
   * Create a goodbye message which includes a name
   * @param {name} String name
   * @return {string} Personalized welcome message
   */

  goodbye = function(name) {
    return console.log('Goodbye ', name);
  };

  hello('Jane');

  hello('John');

  hello('Beep');

  console.log('-----');

  goodbye('Jane');

  goodbye('John');

  goodbye('Beep');


  /**
   * @class Animal
   * Animal class constructor
   * @param {name} Animal name
   * @return {string} Personalized welcome message
   */

  Animal = (function() {

    /**
     * @constructor
     * @param {meters} Amount of meters
     * @return {string} Message
     */
    function Animal(name1) {
      this.name = name1;
    }


    /**
     * @function move
     * Animal move
     * @param {meters} Amount of meters
     * @return {string} Message
     */

    Animal.prototype.move = function(meters) {
      return console.log(this.name + (" moved " + meters + "m."));
    };

    return Animal;

  })();

  dog = new Animal("Jones");

  dog.move(1337);

}).call(this);
